name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        if: ${{ github.event_name == 'push' }}
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.TOKEN_CRUD }}
          service: "crud"